export function cliUsageLines(): readonly string[] {
  return [
    "DeepSeek CLI",
    "Usage:",
    "  deepseek run \"<task>\" [--output text|json|jsonl] [--workspace-root <path>] [--live] [--provider deepseek|glm] [--model <model>] [--thinking off|low|medium|high|xhigh|max] [--tool-projection none|read-only|read-write|safe-all] [--tool-opt-in <category>] [--approval-mode ask|trusted] [--no-tools] [--timeout-ms <ms>] [--output-contract json-object|json-file|file|command-plan]",
    "  deepseek chat [--session <session-id>] [--output text|json|jsonl] [--workspace-root <path>] [--live] [--provider deepseek|glm] [--model <model>] [--thinking off|low|medium|high|xhigh|max] [--tool-projection none|read-only|read-write|safe-all] [--tool-opt-in <category>] [--approval-mode ask|trusted] [--tui auto|line|full-screen|off] [--timeout-ms <ms>]",
    "  deepseek session resume <session-id> [--output text|json]",
    "  deepseek session fork <session-id> [--output text|json]",
    "  deepseek session board <session-id> [--output text|json|jsonl]",
    "  deepseek mcp test <manifest.json> [--enable-real-mcp] [--call <tool> --input <json>] [--output text|json]",
    "  deepseek index-provider status [--output text|json|jsonl]",
    "  deepseek index-provider set <pageindex|zvec|code-index> <enabled|deferred|disabled> [--user] [--output text|json|jsonl]",
    "  deepseek mode [status|agent|workers|verify|plan] [--output text|json|jsonl]",
    "  deepseek memory status|list|candidates|remember|approve|reject|edit|delete|enable|disable|export|explain [args] [--output text|json]",
    "  deepseek context status|grep|describe|summarize|expand|budget|pin [args] [--session <session-id>] [--output text|json|jsonl]",
    "  deepseek checks openspec|typecheck|lint|test|boundaries|build-cli [--output text|json|jsonl]",
    "  deepseek file list|preview|refs <query> [--output text|json|jsonl]",
    "  deepseek repo files|grep|recall|project-index <query> [--output text|json|jsonl]",
    "  deepseek git status|diff|review [--output text|json|jsonl]",
    "  deepseek jump file|text|symbol <query> [--output text|json|jsonl]",
    "  deepseek extension list [--output text|json|jsonl]",
    "  deepseek extension plugin install|verify|snapshot|apply-lockfile <file.json> [--output text|json|jsonl]",
    "  deepseek extension plugin contributions [--output text|json|jsonl]",
    "  deepseek extension skill list|activate [name] [--output text|json|jsonl]",
    "  deepseek extension auth scopes [--output text|json|jsonl]",
    "  deepseek extension mcp test <manifest.json> [--enable-real-mcp] [--call <tool> --input <json>] [--output text|json|jsonl]",
    "  deepseek palette list [--output text|json|jsonl]",
    "  deepseek palette keymap [core|vi-minimal|vi-professional] [--output text|json|jsonl]",
    "  deepseek palette action <action> <target-id> [--output text|json|jsonl]",
    "  deepseek revert preview --request <id>|--turn <id>|--session <id> [--path <path>] [--output text|json|jsonl]",
    "  deepseek revert apply --request <id>|--turn <id>|--session <id> [--path <path>] [--output text|json|jsonl]",
    "  deepseek diagnostics bundle|release|doctor|verify|refresh|evaluate|env|flow|swe-bench|capability-matrix [prepare|inspect|predict|evaluate|run] [--prompt <text>] [--profile <id>] [--task <id>] [--execute] [--baseline <id>] [--instance-file <path>] [--repo-dir <path>] [--output-path <path>] [--predictions-path <path>] [--trace-output-path <jsonl>] [--append-output] [--report-dir <path>] [--run-id <id>] [--instance-id <id>] [--cache-trace-path <jsonl>] [--cache-hit-target <rate>] [--full] [--dry-run] [--live] [--output text|json|jsonl]",
    "  deepseek tools-smoke [--output text|jsonl]",
    "  deepseek <init|config|auth|doctor|privacy|verify-install> [--output text|json]",
    "Notes:",
    "  fact-sensitive run/chat turns classify and select bounded local evidence before model dispatch",
    "  safe-all excludes explicit host opt-in categories by default; use --tool-opt-in network|browser|connector|mcp|media|design|remote when the host permits them",
    "  one-shot run turns use bounded self-repair for repairable failures and emit redacted repair evidence"
  ];
}
